package bolt04

import (
	"crypto/hmac"
	"crypto/sha256"
	"fmt"
	"slices"

	"golang.org/x/crypto/chacha20"

	"github.com/ekzyis/lnpilot/lib/secp256k1"
	"github.com/ekzyis/lnpilot/lightning/lntypes"
)

const (
	OnionPacketPayloadSize = 1300
)

type OnionPacket struct {
	Version      byte
	EphemeralKey *secp256k1.PublicKey
	HopPayloads  [OnionPacketPayloadSize]byte
	HMAC         lntypes.HMAC
}

type Hop struct {
	PubKey  *secp256k1.PublicKey
	Payload []byte
}

type keyType []byte

var (
	// used as key when generating the pseudo-random byte stream that is used to obfuscate the per-hop information
	Rho = keyType{0x72, 0x68, 0x6f}
	// used during the HMAC generation
	Mu = keyType{0x6d, 0x75}
	// used during error reporting
	Um = keyType{0x75, 0x6d}
	// use to generate random filler bytes for the starting mix-header packet
	Pad = keyType{0x70, 0x61, 0x64}
)

func (op *OnionPacket) Serialize() []byte {
	ser := []byte{op.Version}
	ser = append(ser, op.EphemeralKey.SerializeCompressed()...)
	ser = append(ser, op.HopPayloads[:]...)
	ser = append(ser, op.HMAC[:]...)
	return ser
}

func (h *Hop) OnionPayloadLength() int {
	return len(lntypes.BigSize(len(h.Payload)).Encode()) + len(h.Payload) + 32
}

func validateHops(hops []Hop) error {
	var total int
	for _, hop := range hops {
		total += hop.OnionPayloadLength()
		if total > OnionPacketPayloadSize {
			return fmt.Errorf("total onion payload length %d exceeds packet size %d", total, OnionPacketPayloadSize)
		}
	}
	return nil
}

func NewOnionPacket(
	// The session key is the ephemeral key pair generated by the sender. It is
	// used for ECDH with the first hop, and to derive the keys for ECDH with
	// the next hops. Only the session key needs to be communicated to the first
	// hop. Each hop will be able to derive the key for the next hop.
	sessionKey *secp256k1.PrivateKey,
	associatedData []byte,
	hops []Hop,
) (*OnionPacket, error) {
	if err := validateHops(hops); err != nil {
		return nil, err
	}

	var sharedSecrets [][32]byte
	// First ephemeral key is simply the session key. We create a copy here to
	// not mutate the session key in the loop.
	ephemeralKey := secp256k1.PrivKeyFromBytes(sessionKey.Serialize())
	// generate the shared secrets for all hops
	for i := range hops {
		// perform ECDH for shared secret with this hop
		sharedSecret := ecdh(ephemeralKey, hops[i].PubKey)
		sharedSecrets = append(sharedSecrets, sharedSecret)
		// derive ephemeral key for ECDH with next hop
		bf := computeBlindingFactor(ephemeralKey, sharedSecret)
		ephemeralKey.Key.Mul(&bf)
	}

	// Now we generate the hop payloads, starting with the hop payload for the
	// receiving node. A hop payload contains the payload length (without
	// hmac+padding), payload and hmac. Since we're creating an *onion* packet,
	// the hop payload for the first hop contains the hop payloads for all other
	// hops.
	//
	// We initialize the hop payload with the padding, which consists of
	// deterministic random bytes generated by the stream cipher.
	//
	// (The spec calls the hop payload "mix-header".)
	padding := _chacha20([32]byte(sessionKey.Serialize()), Pad, OnionPacketPayloadSize)
	hopPayload := make([]byte, OnionPacketPayloadSize)
	copy(hopPayload, padding)

	// HMAC for each layer. For the receiving node, the HMAC is just 32 zero
	// bytes, since it doesn't need to pass any payload with HMAC to another
	// node. That's also how it knows that it's the last hop.
	var hmac lntypes.HMAC

	// Iterate through hops in reverse order (last hop first)
	for i := len(hops) - 1; i >= 0; i-- {
		hop := hops[i]

		// We add the payload length, payload and HMAC to the beginning and make
		// sure the packet length is kept the same by shifting.
		pl := hop.Payload
		plEncodedLength := lntypes.BigSize(len(pl)).Encode()
		prepend := slices.Concat(plEncodedLength, pl, hmac[:])
		shiftRight(hopPayload, len(prepend))
		copy(hopPayload[:len(prepend)], prepend)

		// Encrypt
		ss := sharedSecrets[i]
		stream := _chacha20(ss, Rho, len(hopPayload))
		hopPayload = xor(hopPayload, stream)

		if i == len(hops)-1 {
			// Every hop will peel one layer off the onion. To keep the size
			// fixed, the packet is padded to 2x size before decrypting it.
			// Before passing it on, the packet is then truncated back to the
			// original size. If we don't consider this when constructing the
			// onion, HMAC verification will fail after the first hop. This is
			// why the "filler" is needed. Big oof.
			filler := generateFiller(sharedSecrets, hops)
			copy(hopPayload[len(hopPayload)-len(filler):], filler)
		}

		// Add associated data and calculate HMAC of this hop payload for hop
		// payload in next iteration.
		hmacPayload := append(hopPayload, associatedData...)
		hmac = _hmac(hmacPayload, ss)
	}

	packet := &OnionPacket{
		Version:      0x00,
		EphemeralKey: sessionKey.PubKey(),
		HopPayloads:  [1300]byte(hopPayload),
		HMAC:         hmac,
	}
	return packet, nil
}

func generateFiller(secrets [][32]byte, hops []Hop) []byte {
	fillerLen := 0
	for i := 0; i < len(hops)-1; i++ {
		fillerLen += hops[i].OnionPayloadLength()
	}
	filler := make([]byte, fillerLen)

	streamOffset := 0
	for i := 0; i < len(hops)-1; i++ {
		hop := hops[i]
		ss := secrets[i]
		stream := _chacha20(ss, Rho, 2*OnionPacketPayloadSize)
		streamStart := OnionPacketPayloadSize - streamOffset
		streamEnd := OnionPacketPayloadSize + hop.OnionPayloadLength()
		filler = xor(filler, stream[streamStart:streamEnd])
		streamOffset += hop.OnionPayloadLength()
	}

	return filler
}

func _chacha20(secret [32]byte, keyType keyType, n int) []byte {
	// using the same 96-bit nonce is safe because we never reuse keys
	nonce := make([]byte, 12)
	key := deriveKey(secret, keyType)
	cipher, err := chacha20.NewUnauthenticatedCipher(key, nonce)
	if err != nil {
		// should only panic if key or nonce have wrong length
		panic(err)
	}
	output := make([]byte, n)
	cipher.XORKeyStream(output, output)
	return output
}

func deriveKey(secret [32]byte, keyType keyType) []byte {
	h := hmac.New(sha256.New, []byte(keyType[:]))
	h.Write(secret[:])
	key := h.Sum(nil)
	return key
}

func shiftRight(dst []byte, shift int) {
	copy(dst[shift:], dst[:len(dst)-shift])
}

func _hmac(msg []byte, secret [32]byte) lntypes.HMAC {
	key := deriveKey(secret, Mu)
	h := hmac.New(sha256.New, key)
	h.Write(msg)
	return lntypes.HMAC(h.Sum(nil))
}

func xor(a, b []byte) []byte {
	output := make([]byte, max(len(a), len(b)))
	for i := 0; i < min(len(a), len(b)); i++ {
		output[i] = a[i] ^ b[i]
	}
	// copy remaining bytes from the longer slice
	if len(a) > len(b) {
		copy(output[len(b):], a[len(b):])
	} else if len(b) > len(a) {
		copy(output[len(a):], b[len(a):])
	}
	return output
}

func ecdh(privKey *secp256k1.PrivateKey, pubKey *secp256k1.PublicKey) [32]byte {
	// Unfortunately, secp256k1.GenerateSharedSecret() only returns X, not the
	// compressed public key, so we perform ECDH ourselves here.
	// TODO: provide helper function for this in lib/secp256k1
	var point, result secp256k1.JacobianPoint
	pubKey.AsJacobian(&point)
	secp256k1.ScalarMultNonConst(&privKey.Key, &point, &result)
	result.ToAffine()
	sharedPoint := secp256k1.NewPublicKey(&result.X, &result.Y)
	return sha256.Sum256(sharedPoint.SerializeCompressed())
}

func computeBlindingFactor(ephemeralKey *secp256k1.PrivateKey, ss [32]byte) secp256k1.ModNScalar {
	var blindingFactor secp256k1.ModNScalar
	sha := sha256.New()
	sha.Write(ephemeralKey.PubKey().SerializeCompressed())
	sha.Write(ss[:])
	blindingFactor.SetByteSlice(sha.Sum(nil))
	return blindingFactor
}
